export const ITEMS = "ITEMS";
export const MORE_ITEMS = "MORE_ITEMS";
export const LOAD_MORE_ITEMS_BUTTON_IS_DISABLED = "LOAD_MORE_ITEMS_BUTTON_IS_DISABLED";
export const RESOURCE = "RESOURCE";
export const PEOPLE = "PEOPLE";
export const PLANETS = "PLANETS";
export const STARSHIPS = "STARSHIPS";
export const LOADING = "LOADING";
export const GET_ITEMS_CREATOR = "GET_ITEMS_CREATOR";
export const GET_MORE_ITEMS_CREATOR = "GET_MORE_ITEMS_CREATOR";



